"""Portable Markdown and CSV exports."""

from __future__ import annotations

import csv
import io
from typing import Any

from .constants import ASSESSMENT_DIMENSIONS
from .planning import build_replication_plan
from .scoring import evidence_matrix
from .workspace import Workspace


def matrix_csv(workspace: Workspace) -> str:
    """Export the evidence matrix using the standard csv module."""
    matrix = evidence_matrix(workspace)
    fieldnames = ["paper_id", "title", "year", *matrix["dimensions"]]
    output = io.StringIO(newline="")
    writer = csv.DictWriter(output, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()
    writer.writerows(matrix["rows"])
    return output.getvalue()


def plan_markdown(workspace: Workspace) -> str:
    """Render a readable replication plan for issues, meetings, or lab notebooks."""
    plan = build_replication_plan(workspace)
    manifest = workspace.manifest()
    lines = [
        f"# Replication plan: {manifest['title']}",
        "",
        f"**Research question:** {manifest['research_question']}",
        "",
        (
            f"{plan['summary']['task_count']} tasks · "
            f"{plan['summary']['total_effort_hours']} estimated hours · "
            f"{plan['summary']['blocked_count']} blocked"
        ),
        "",
    ]
    for wave in plan["waves"]:
        lines.extend([f"## Wave {wave['wave'] + 1}", ""])
        for task in wave["parallel_tasks"]:
            dependencies = ", ".join(task.get("depends_on", [])) or "none"
            lines.extend(
                [
                    f"### {task['title']}",
                    "",
                    f"- ID: `{task['id']}`",
                    f"- State: {task.get('state', 'ready')}",
                    f"- Priority: {task.get('priority', 'medium')}",
                    f"- Estimate: {task.get('estimate_hours', 0)} hours",
                    f"- Depends on: {dependencies}",
                    f"- Acceptance: {task.get('acceptance', 'Not recorded.')}",
                    "",
                ]
            )
    lines.extend(
        [
            "## Interpretation boundary",
            "",
            plan["assumption"],
            "",
            "Generated by ReproWeave. Estimates remain human-entered planning assumptions.",
            "",
        ]
    )
    return "\n".join(lines)


def assessment_markdown(assessment: dict[str, Any], paper: dict[str, Any]) -> str:
    """Render one transparent assessment card."""
    lines = [f"# Reconstructability card: {paper['title']}", ""]
    for dimension, metadata in ASSESSMENT_DIMENSIONS.items():
        detail = assessment.get("ratings", {}).get(dimension)
        rating = detail["rating"] if detail else "missing"
        evidence = detail["evidence"] if detail else "No evidence recorded."
        lines.extend(
            [
                f"## {metadata['label']}: {rating.upper()}",
                "",
                metadata["question"],
                "",
                f"Evidence: {evidence}",
                "",
            ]
        )
    lines.extend(
        [
            "> ReproWeave assesses documented reconstructability, not scientific quality, "
            "correctness, novelty, or integrity.",
            "",
        ]
    )
    return "\n".join(lines)
